/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#ffe088",
        "on-tertiary-container": "#ab7c00",
        "error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "inverse-surface": "#313030",
        "on-primary-container": "#858383",
        "surface-container-high": "#ebe7e7",
        "on-error-container": "#93000a",
        "surface-container": "#f0edec",
        "on-surface": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed": "#241a00",
        "secondary-container": "#fed65b",
        "tertiary": "#000000",
        "primary-container": "#1c1b1b",
        "outline": "#747878",
        "on-error": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "surface": "#fcf9f8",
        "outline-variant": "#c4c7c7",
        "on-secondary-container": "#745c00",
        "secondary": "#735c00",
        "primary": "#000000",
        "tertiary-container": "#271900",
        "surface-container-highest": "#e5e2e1",
        "on-surface-variant": "#444748",
        "on-tertiary-fixed": "#271900",
        "surface-tint": "#5f5e5e",
        "surface-container-low": "#f6f3f2",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-secondary-fixed-variant": "#574500",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed-dim": "#f7bd48",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "tertiary-fixed": "#ffdea6",
        "error": "#ba1a1a",
        "background": "#fcf9f8",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
    },
  },
  plugins: [],
}